# From actions/ftp-deploy https://github.com/marketplace/actions/ftp-deploy
on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: ğŸ”¨ Build Project
      env: 
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
      run: |
        echo "Copying Github Secret to .env file"
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        npm install
        npm run build
    
    # - name: ğŸ“‚ Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ${{ secrets.ftp_server }}
    #     username: ${{ secrets.ftp_username }}
    #     password: ${{ secrets.ftp_password }}
    #     server-dir: '/_dev/search-satellite-imagery/test/'
    #     local-dir: './dist/'
    #     dry-run: false
    #     log-level: verbose
    #     protocol: ftp
    #     port: 21
    
    - name: ğŸ“¦ Get LFTP
      run: sudo apt install lftp
    - name: ğŸ› ï¸ Configure LFTP
      run: mkdir ~/.lftp && echo "set ssl:verify-certificate false; && set ftp:passive-mode off;" >> ~/.lftp/rc
    # - name: ğŸ”‘ Load Secrets
    #   run: echo "machine ${{ secrets.FTP_HOSTNAME }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc
    # - name: ğŸ“„ Upload File
    #   run: lftp -e "put -O /destination/ ./README.md" ${{ secrets.FTP_HOSTNAME }}
    - name: ğŸ“ Upload Folder
      run: lftp --script=- --user ${{ secrets.ftp_username }} --password ${{ secrets.ftp_password }} -e "mirror --parallel=100 -R ./dist/ /_dev/search-satellite-imagery/test/" ${{ secrets.ftp_server }}
